import './globals.css'
import Provider from './provider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark" style={{ colorScheme: "dark" }}>
      <body>
        <Provider>
          <div className='flex justify-between items-center p-4'>
            <div>
              {children}
            </div>
          </div>
        </Provider>
      </body>
    </html>
  )
}
