import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from './provider'; // Add this line or the appropriate import for your Provider
import CustomConvexClientProvider from './ConvexClientProvider'; // Import CustomConvexClientProvider

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        
      >
        <CustomConvexClientProvider>
          <Provider>
            {children}
          </Provider>
        </CustomConvexClientProvider>
      </body>
    </html>
  );
}